# Generated by Django 4.2.4 on 2023-09-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0002_locations_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='place_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
