# Generated by Django 4.2.4 on 2023-09-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0005_distances_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distances',
            name='duration_traffic_mins',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
