# Generated by Django 4.2.4 on 2023-09-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_content', '0006_alter_distances_duration_traffic_mins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distances',
        ),
    ]
